### ISSUE TITLE
link to algorithm is broken

### ISSUE THREAD

**Issue by mcnuttandrew** [substack/point-in-polygon#12]
Going to https://www.ecse.rpi.edu/Homepages/wrf/Research/Short_Notes/pnpoly.html  gives a 404

Possible alternate link
https://pdfs.semanticscholar.org/f232/78f51e2a27fa58b09f814cd1a5bd20059674.pdf

**Comment by athlan** [comment]
PR raised
https://github.com/substack/point-in-polygon/pull/13

**Comment by suiluj** [comment]
i think this link is the right one:
https://wrf.ecse.rpi.edu//Research/Short_Notes/pnpoly.html

**Comment by substack** [comment]
1.0.2
