### ISSUE TITLE
Inaccurate results when point is on the edge

### ISSUE THREAD

**Issue by jgberg** [substack/point-in-polygon#2]
If you try a point on the edge you will get inconsistent results...
For example compare the results you get for:
[1,1] vs [2,2] for a polygon: [ [1, 1], [ 2,1 ], [ 2,2], [1,2] ];

They are both on an edge and yet they give different results

**Comment by mattdesl** [comment]
This is an old issue... but for robust checks a different module should be used:  
[robust-point-in-polygon](https://www.npmjs.com/package/robust-point-in-polygon)

The lack of numerical robustness should be noted in this module's readme. In some cases (e.g. game development) you might not want to use a robust solution.

**Comment by ralph1898** [comment]
in the "winding number inclusion" method:
1 - adding some lines in the func "isLeft" to determine if the point is on the segment or not; you may create a new marker to monitor "when isLeft == 0, you should set the marker with 1 if the point on the segment".
2 - adding a condition between "checking if isLeft > 0" and "++wn", which is to check the marker aforementioned. If the marker is 1, give some non-zero value to wn, then break the loop.
