### ISSUE TITLE
How can I use this code in plain html/JS page, without any "node"?

### ISSUE THREAD

**Issue by depesz** [substack/point-in-polygon#21]
Hi,
I'm normally DBA, but for fun i decided to play with HTML canvas. The thing I'm working on requires checking if given point is within polygon, which seems to be what your code does, but apparently I can't just load the .js in html, and be happy, as then it errors out with:

    Uncaught ReferenceError: require is not defined

Is there anything I could do to use your module in my plain html/js thing?

**Comment by darve** [comment]
Bit rude to be honest mate. Glad you figured it out.

**Comment by depesz** [comment]
I'm sorry - wasn't my intention. Closed the issue as didn't want to waste your time. I do apologize.
