### ISSUE TITLE
which is longitude and which is latitude

### ISSUE THREAD

**Issue by deepaksisodiya** [substack/point-in-polygon#4]
var polygon = [ [ 1, 1 ], [ 1, 2 ], [ 2, 2 ], [ 2, 1 ] ];

console.dir([
    inside([ 1.5, 1.5 ], polygon),
    inside([ 4.9, 1.2 ], polygon),
    inside([ 1.8, 1.1 ], polygon)
]);

here , How can i know , which is longitude and which is latitude

**Comment by pieterjandesmedt** [comment]
It's the same whether you use `[lat, lng]` or `[lng, lat]`, but be consequent: the order of the point coordinates has to be the same as the order of the polygon vertex coordinates.

I use `[lng, lat]` as per the [geojson specifications](http://geojson.org/).

**Comment by deepaksisodiya** [comment]
Thanks @pieterjandesmedt
